
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Use Node
        uses: actions/setup-node@master
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies using Yarn
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Publish Canary
        env: # Or as an environment variable
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
            if [ "${{github.repository}}" == "ardatan/graphql-toolkit" ] && [ "${{ secrets.NODE_AUTH_TOKEN }}" != "" ]
            then
                yarn ci:release:canary --yes --registry https://registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
            else    
                echo "Fork PR: ${{github.repository}}"
                echo "Skipping canary publish due to a fork/PR..."
            fi
